<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="27" ignored="0" total="57" passed="17" failed="13" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-05-26T19:48:02 CDT" name="Suite" finished-at="2025-05-26T19:50:02 CDT" duration-ms="120737">
    <groups>
      <group name="datadriven">
        <method signature="TC02_Login.testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@561868a0]" name="testLogin" class="testCases.TC02_Login"/>
        <method signature="TC02_Login.testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@33fe57a9]" name="testLogin" class="testCases.TC02_Login"/>
        <method signature="TC02_Login.testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@61a88b8c]" name="testLogin" class="testCases.TC02_Login"/>
      </group> <!-- datadriven -->
      <group name="regression">
        <method signature="TC01_LaunchApplication.testLaunchApplication()[pri:0, instance:testCases.TC01_LaunchApplication@1fde5d22]" name="testLaunchApplication" class="testCases.TC01_LaunchApplication"/>
        <method signature="TC02_Login.testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@561868a0]" name="testLogin" class="testCases.TC02_Login"/>
        <method signature="TC03_AddToCart.testAddToCart()[pri:0, instance:testCases.TC03_AddToCart@47f9738]" name="testAddToCart" class="testCases.TC03_AddToCart"/>
        <method signature="TC04_CompletePurchase.testCompletePurchase()[pri:0, instance:testCases.TC04_CompletePurchase@2ea6e30c]" name="testCompletePurchase" class="testCases.TC04_CompletePurchase"/>
        <method signature="TC05_AddToWishList.testAddToWishList()[pri:0, instance:testCases.TC05_AddToWishList@6155d082]" name="testAddToWishList" class="testCases.TC05_AddToWishList"/>
        <method signature="TC06_AddAffiliate.testAddAffiliate()[pri:0, instance:testCases.TC06_AddAffiliate@3a5ecce3]" name="testAddAffiliate" class="testCases.TC06_AddAffiliate"/>
        <method signature="TC01_LaunchApplication.testLaunchApplication()[pri:0, instance:testCases.TC01_LaunchApplication@22d7b4f8]" name="testLaunchApplication" class="testCases.TC01_LaunchApplication"/>
        <method signature="TC02_Login.testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@33fe57a9]" name="testLogin" class="testCases.TC02_Login"/>
        <method signature="TC03_AddToCart.testAddToCart()[pri:0, instance:testCases.TC03_AddToCart@149dd36b]" name="testAddToCart" class="testCases.TC03_AddToCart"/>
        <method signature="TC04_CompletePurchase.testCompletePurchase()[pri:0, instance:testCases.TC04_CompletePurchase@4982cc36]" name="testCompletePurchase" class="testCases.TC04_CompletePurchase"/>
        <method signature="TC05_AddToWishList.testAddToWishList()[pri:0, instance:testCases.TC05_AddToWishList@38831718]" name="testAddToWishList" class="testCases.TC05_AddToWishList"/>
        <method signature="TC06_AddAffiliate.testAddAffiliate()[pri:0, instance:testCases.TC06_AddAffiliate@2c1156a7]" name="testAddAffiliate" class="testCases.TC06_AddAffiliate"/>
        <method signature="TC01_LaunchApplication.testLaunchApplication()[pri:0, instance:testCases.TC01_LaunchApplication@4f1bfe23]" name="testLaunchApplication" class="testCases.TC01_LaunchApplication"/>
        <method signature="TC02_Login.testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@61a88b8c]" name="testLogin" class="testCases.TC02_Login"/>
        <method signature="TC03_AddToCart.testAddToCart()[pri:0, instance:testCases.TC03_AddToCart@e19bb76]" name="testAddToCart" class="testCases.TC03_AddToCart"/>
        <method signature="TC04_CompletePurchase.testCompletePurchase()[pri:0, instance:testCases.TC04_CompletePurchase@22295ec4]" name="testCompletePurchase" class="testCases.TC04_CompletePurchase"/>
        <method signature="TC05_AddToWishList.testAddToWishList()[pri:0, instance:testCases.TC05_AddToWishList@512535ff]" name="testAddToWishList" class="testCases.TC05_AddToWishList"/>
        <method signature="TC06_AddAffiliate.testAddAffiliate()[pri:0, instance:testCases.TC06_AddAffiliate@71529963]" name="testAddAffiliate" class="testCases.TC06_AddAffiliate"/>
      </group> <!-- regression -->
      <group name="sanity">
        <method signature="TC01_LaunchApplication.testLaunchApplication()[pri:0, instance:testCases.TC01_LaunchApplication@1fde5d22]" name="testLaunchApplication" class="testCases.TC01_LaunchApplication"/>
        <method signature="TC02_Login.testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@561868a0]" name="testLogin" class="testCases.TC02_Login"/>
        <method signature="TC03_AddToCart.testAddToCart()[pri:0, instance:testCases.TC03_AddToCart@47f9738]" name="testAddToCart" class="testCases.TC03_AddToCart"/>
        <method signature="TC04_CompletePurchase.testCompletePurchase()[pri:0, instance:testCases.TC04_CompletePurchase@2ea6e30c]" name="testCompletePurchase" class="testCases.TC04_CompletePurchase"/>
        <method signature="TC01_LaunchApplication.testLaunchApplication()[pri:0, instance:testCases.TC01_LaunchApplication@22d7b4f8]" name="testLaunchApplication" class="testCases.TC01_LaunchApplication"/>
        <method signature="TC02_Login.testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@33fe57a9]" name="testLogin" class="testCases.TC02_Login"/>
        <method signature="TC03_AddToCart.testAddToCart()[pri:0, instance:testCases.TC03_AddToCart@149dd36b]" name="testAddToCart" class="testCases.TC03_AddToCart"/>
        <method signature="TC04_CompletePurchase.testCompletePurchase()[pri:0, instance:testCases.TC04_CompletePurchase@4982cc36]" name="testCompletePurchase" class="testCases.TC04_CompletePurchase"/>
        <method signature="TC01_LaunchApplication.testLaunchApplication()[pri:0, instance:testCases.TC01_LaunchApplication@4f1bfe23]" name="testLaunchApplication" class="testCases.TC01_LaunchApplication"/>
        <method signature="TC02_Login.testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@61a88b8c]" name="testLogin" class="testCases.TC02_Login"/>
        <method signature="TC03_AddToCart.testAddToCart()[pri:0, instance:testCases.TC03_AddToCart@e19bb76]" name="testAddToCart" class="testCases.TC03_AddToCart"/>
        <method signature="TC04_CompletePurchase.testCompletePurchase()[pri:0, instance:testCases.TC04_CompletePurchase@22295ec4]" name="testCompletePurchase" class="testCases.TC04_CompletePurchase"/>
      </group> <!-- sanity -->
    </groups>
    <test started-at="2025-05-26T19:48:02 CDT" name="firefoxTest" finished-at="2025-05-26T19:49:50 CDT" duration-ms="108713">
      <class name="testCases.TC02_Login">
        <test-method is-config="true" signature="openApp(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@33fe57a9]" started-at="2025-05-26T19:49:25 CDT" name="openApp" finished-at="2025-05-26T19:49:31 CDT" duration-ms="6279" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method signature="testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@33fe57a9]" started-at="2025-05-26T19:49:31 CDT" name="testLogin" data-provider="LoginData" finished-at="2025-05-26T19:49:33 CDT" duration-ms="1891" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[smitasharma.qa@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[ss*QA123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method signature="testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@33fe57a9]" started-at="2025-05-26T19:49:33 CDT" name="testLogin" data-provider="LoginData" finished-at="2025-05-26T19:49:35 CDT" duration-ms="1638" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[nona@yahoo.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[QWER!@#$]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method signature="testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@33fe57a9]" started-at="2025-05-26T19:49:35 CDT" name="testLogin" data-provider="LoginData" finished-at="2025-05-26T19:49:36 CDT" duration-ms="1577" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[sid@cloudberry.services]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Test123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method signature="testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@33fe57a9]" started-at="2025-05-26T19:49:36 CDT" name="testLogin" data-provider="LoginData" finished-at="2025-05-26T19:49:38 CDT" duration-ms="1382" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[apushedwoman@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[password123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method signature="testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@33fe57a9]" started-at="2025-05-26T19:49:38 CDT" name="testLogin" data-provider="LoginData" finished-at="2025-05-26T19:49:40 CDT" duration-ms="1927" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[hichamkhachiai@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[hicham123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method is-config="true" signature="closeApp()[pri:0, instance:testCases.TC02_Login@33fe57a9]" started-at="2025-05-26T19:49:40 CDT" name="closeApp" finished-at="2025-05-26T19:49:42 CDT" duration-ms="2107" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- testCases.TC02_Login -->
      <class name="testCases.TC05_AddToWishList">
        <test-method is-config="true" signature="openApp(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC05_AddToWishList@38831718]" started-at="2025-05-26T19:48:30 CDT" name="openApp" finished-at="2025-05-26T19:48:37 CDT" duration-ms="7049" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method retried="true" signature="testAddToWishList()[pri:0, instance:testCases.TC05_AddToWishList@38831718]" started-at="2025-05-26T19:48:37 CDT" name="testAddToWishList" finished-at="2025-05-26T19:48:49 CDT" duration-ms="12520" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed due to unexpected exception.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed due to unexpected exception.
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC05_AddToWishList.testAddToWishList(TC05_AddToWishList.java:77)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddToWishList -->
        <test-method retried="true" signature="testAddToWishList()[pri:0, instance:testCases.TC05_AddToWishList@38831718]" started-at="2025-05-26T19:48:49 CDT" name="testAddToWishList" finished-at="2025-05-26T19:48:59 CDT" duration-ms="10335" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed due to unexpected exception.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed due to unexpected exception.
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC05_AddToWishList.testAddToWishList(TC05_AddToWishList.java:77)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddToWishList -->
        <test-method signature="testAddToWishList()[pri:0, instance:testCases.TC05_AddToWishList@38831718]" started-at="2025-05-26T19:48:59 CDT" name="testAddToWishList" finished-at="2025-05-26T19:49:10 CDT" duration-ms="10249" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed due to unexpected exception.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed due to unexpected exception.
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC05_AddToWishList.testAddToWishList(TC05_AddToWishList.java:77)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddToWishList -->
        <test-method is-config="true" signature="closeApp()[pri:0, instance:testCases.TC05_AddToWishList@38831718]" started-at="2025-05-26T19:49:10 CDT" name="closeApp" finished-at="2025-05-26T19:49:11 CDT" duration-ms="1540" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- testCases.TC05_AddToWishList -->
      <class name="testCases.TC01_LaunchApplication">
        <test-method is-config="true" signature="openApp(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC01_LaunchApplication@22d7b4f8]" started-at="2025-05-26T19:48:02 CDT" name="openApp" finished-at="2025-05-26T19:48:11 CDT" duration-ms="9395" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method signature="testLaunchApplication()[pri:0, instance:testCases.TC01_LaunchApplication@22d7b4f8]" started-at="2025-05-26T19:48:11 CDT" name="testLaunchApplication" finished-at="2025-05-26T19:48:11 CDT" duration-ms="89" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLaunchApplication -->
        <test-method is-config="true" signature="closeApp()[pri:0, instance:testCases.TC01_LaunchApplication@22d7b4f8]" started-at="2025-05-26T19:48:11 CDT" name="closeApp" finished-at="2025-05-26T19:48:15 CDT" duration-ms="3920" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- testCases.TC01_LaunchApplication -->
      <class name="testCases.TC03_AddToCart">
        <test-method is-config="true" signature="openApp(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC03_AddToCart@149dd36b]" started-at="2025-05-26T19:48:15 CDT" name="openApp" finished-at="2025-05-26T19:48:22 CDT" duration-ms="7103" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method retried="true" signature="testAddToCart()[pri:0, instance:testCases.TC03_AddToCart@149dd36b]" started-at="2025-05-26T19:48:22 CDT" name="testAddToCart" finished-at="2025-05-26T19:48:25 CDT" duration-ms="2519" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed due to unexpected exception.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed due to unexpected exception.
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC03_AddToCart.testAddToCart(TC03_AddToCart.java:55)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddToCart -->
        <test-method retried="true" signature="testAddToCart()[pri:0, instance:testCases.TC03_AddToCart@149dd36b]" started-at="2025-05-26T19:48:25 CDT" name="testAddToCart" finished-at="2025-05-26T19:48:25 CDT" duration-ms="203" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed due to unexpected exception.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed due to unexpected exception.
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC03_AddToCart.testAddToCart(TC03_AddToCart.java:55)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddToCart -->
        <test-method signature="testAddToCart()[pri:0, instance:testCases.TC03_AddToCart@149dd36b]" started-at="2025-05-26T19:48:25 CDT" name="testAddToCart" finished-at="2025-05-26T19:48:26 CDT" duration-ms="1265" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed due to unexpected exception.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed due to unexpected exception.
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC03_AddToCart.testAddToCart(TC03_AddToCart.java:55)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddToCart -->
        <test-method is-config="true" signature="closeApp()[pri:0, instance:testCases.TC03_AddToCart@149dd36b]" started-at="2025-05-26T19:48:27 CDT" name="closeApp" finished-at="2025-05-26T19:48:30 CDT" duration-ms="2890" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- testCases.TC03_AddToCart -->
      <class name="testCases.TC06_AddAffiliate">
        <test-method is-config="true" signature="openApp(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC06_AddAffiliate@2c1156a7]" started-at="2025-05-26T19:49:11 CDT" name="openApp" finished-at="2025-05-26T19:49:17 CDT" duration-ms="5646" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method signature="testAddAffiliate()[pri:0, instance:testCases.TC06_AddAffiliate@2c1156a7]" started-at="2025-05-26T19:49:17 CDT" name="testAddAffiliate" finished-at="2025-05-26T19:49:22 CDT" duration-ms="5001" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddAffiliate -->
        <test-method is-config="true" signature="closeApp()[pri:0, instance:testCases.TC06_AddAffiliate@2c1156a7]" started-at="2025-05-26T19:49:22 CDT" name="closeApp" finished-at="2025-05-26T19:49:25 CDT" duration-ms="2607" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- testCases.TC06_AddAffiliate -->
      <class name="testCases.TC04_CompletePurchase">
        <test-method is-config="true" signature="openApp(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC04_CompletePurchase@4982cc36]" started-at="2025-05-26T19:49:42 CDT" name="openApp" finished-at="2025-05-26T19:49:47 CDT" duration-ms="4855" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method retried="true" signature="testCompletePurchase()[pri:0, instance:testCases.TC04_CompletePurchase@4982cc36]" started-at="2025-05-26T19:49:47 CDT" name="testCompletePurchase" finished-at="2025-05-26T19:49:48 CDT" duration-ms="1457" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed due to unexpected exception.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed due to unexpected exception.
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC04_CompletePurchase.testCompletePurchase(TC04_CompletePurchase.java:81)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCompletePurchase -->
        <test-method retried="true" signature="testCompletePurchase()[pri:0, instance:testCases.TC04_CompletePurchase@4982cc36]" started-at="2025-05-26T19:49:48 CDT" name="testCompletePurchase" finished-at="2025-05-26T19:49:48 CDT" duration-ms="84" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed due to unexpected exception.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed due to unexpected exception.
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC04_CompletePurchase.testCompletePurchase(TC04_CompletePurchase.java:81)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCompletePurchase -->
        <test-method signature="testCompletePurchase()[pri:0, instance:testCases.TC04_CompletePurchase@4982cc36]" started-at="2025-05-26T19:49:48 CDT" name="testCompletePurchase" finished-at="2025-05-26T19:49:48 CDT" duration-ms="69" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed due to unexpected exception.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed due to unexpected exception.
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC04_CompletePurchase.testCompletePurchase(TC04_CompletePurchase.java:81)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCompletePurchase -->
        <test-method is-config="true" signature="closeApp()[pri:0, instance:testCases.TC04_CompletePurchase@4982cc36]" started-at="2025-05-26T19:49:49 CDT" name="closeApp" finished-at="2025-05-26T19:49:50 CDT" duration-ms="1770" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- testCases.TC04_CompletePurchase -->
    </test> <!-- firefoxTest -->
    <test started-at="2025-05-26T19:48:02 CDT" name="chromeTest" finished-at="2025-05-26T19:49:52 CDT" duration-ms="110723">
      <class name="testCases.TC02_Login">
        <test-method is-config="true" signature="openApp(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@561868a0]" started-at="2025-05-26T19:48:44 CDT" name="openApp" finished-at="2025-05-26T19:48:48 CDT" duration-ms="3597" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method retried="true" signature="testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@561868a0]" started-at="2025-05-26T19:48:49 CDT" name="testLogin" data-provider="LoginData" finished-at="2025-05-26T19:48:51 CDT" duration-ms="2272" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[smitasharma.qa@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[ss*QA123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unexpected exception during login for email: smitasharma.qa@gmail.com. Exception: element click intercepted: Element is not clickable at point (860, 571)
  (Session info: chrome=136.0.7103.114)
Build info: version: '4.31.0', revision: '1ef9f18787*'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.6'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [78cc5f1a1db475e43cbf047e506025f0, clickElement {id=f.23F93CE1BF93211E4D645FB6F692C8E1.d.7C4E72AB3D88D4FA5FF824DDFC8ACB9D.e.25}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 136.0.7103.114, chrome: {chromedriverVersion: 136.0.7103.113 (76fa3c17824..., userDataDir: C:\Users\ssmit\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:49721}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: Windows 10, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://192.168.1.191:4444/ses..., se:cdpVersion: 136.0.7103.114, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[RemoteWebDriver: chrome on Windows 10 (78cc5f1a1db475e43cbf047e506025f0)] -> xpath: //button[normalize-space()='Login']]
Session ID: 78cc5f1a1db475e43cbf047e506025f0. Screenshot: C:\Users\ssmit\eclipse-workspace\NinjaV5\screenshots\exception_smitasharma_qa_gmail_com_20250526074851.png]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unexpected exception during login for email: smitasharma.qa@gmail.com. Exception: element click intercepted: Element is not clickable at point (860, 571)
  (Session info: chrome=136.0.7103.114)
Build info: version: '4.31.0', revision: '1ef9f18787*'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.6'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [78cc5f1a1db475e43cbf047e506025f0, clickElement {id=f.23F93CE1BF93211E4D645FB6F692C8E1.d.7C4E72AB3D88D4FA5FF824DDFC8ACB9D.e.25}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 136.0.7103.114, chrome: {chromedriverVersion: 136.0.7103.113 (76fa3c17824..., userDataDir: C:\Users\ssmit\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:49721}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: Windows 10, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://192.168.1.191:4444/ses..., se:cdpVersion: 136.0.7103.114, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[RemoteWebDriver: chrome on Windows 10 (78cc5f1a1db475e43cbf047e506025f0)] -> xpath: //button[normalize-space()='Login']]
Session ID: 78cc5f1a1db475e43cbf047e506025f0. Screenshot: C:\Users\ssmit\eclipse-workspace\NinjaV5\screenshots\exception_smitasharma_qa_gmail_com_20250526074851.png
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC02_Login.testLogin(TC02_Login.java:70)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method retried="true" signature="testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@561868a0]" started-at="2025-05-26T19:48:51 CDT" name="testLogin" data-provider="LoginData" finished-at="2025-05-26T19:48:53 CDT" duration-ms="1764" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[smitasharma.qa@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[ss*QA123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unexpected exception during login for email: smitasharma.qa@gmail.com. Exception: element click intercepted: Element is not clickable at point (860, 571)
  (Session info: chrome=136.0.7103.114)
Build info: version: '4.31.0', revision: '1ef9f18787*'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.6'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [78cc5f1a1db475e43cbf047e506025f0, clickElement {id=f.23F93CE1BF93211E4D645FB6F692C8E1.d.0DAFD8E9B6907256CE283171BD5EA740.e.71}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 136.0.7103.114, chrome: {chromedriverVersion: 136.0.7103.113 (76fa3c17824..., userDataDir: C:\Users\ssmit\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:49721}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: Windows 10, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://192.168.1.191:4444/ses..., se:cdpVersion: 136.0.7103.114, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[RemoteWebDriver: chrome on Windows 10 (78cc5f1a1db475e43cbf047e506025f0)] -> xpath: //button[normalize-space()='Login']]
Session ID: 78cc5f1a1db475e43cbf047e506025f0. Screenshot: C:\Users\ssmit\eclipse-workspace\NinjaV5\screenshots\exception_smitasharma_qa_gmail_com_20250526074853.png]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unexpected exception during login for email: smitasharma.qa@gmail.com. Exception: element click intercepted: Element is not clickable at point (860, 571)
  (Session info: chrome=136.0.7103.114)
Build info: version: '4.31.0', revision: '1ef9f18787*'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.6'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [78cc5f1a1db475e43cbf047e506025f0, clickElement {id=f.23F93CE1BF93211E4D645FB6F692C8E1.d.0DAFD8E9B6907256CE283171BD5EA740.e.71}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 136.0.7103.114, chrome: {chromedriverVersion: 136.0.7103.113 (76fa3c17824..., userDataDir: C:\Users\ssmit\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:49721}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: Windows 10, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://192.168.1.191:4444/ses..., se:cdpVersion: 136.0.7103.114, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[RemoteWebDriver: chrome on Windows 10 (78cc5f1a1db475e43cbf047e506025f0)] -> xpath: //button[normalize-space()='Login']]
Session ID: 78cc5f1a1db475e43cbf047e506025f0. Screenshot: C:\Users\ssmit\eclipse-workspace\NinjaV5\screenshots\exception_smitasharma_qa_gmail_com_20250526074853.png
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC02_Login.testLogin(TC02_Login.java:70)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method signature="testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@561868a0]" started-at="2025-05-26T19:48:53 CDT" name="testLogin" data-provider="LoginData" finished-at="2025-05-26T19:48:54 CDT" duration-ms="1691" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[smitasharma.qa@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[ss*QA123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unexpected exception during login for email: smitasharma.qa@gmail.com. Exception: element click intercepted: Element is not clickable at point (860, 571)
  (Session info: chrome=136.0.7103.114)
Build info: version: '4.31.0', revision: '1ef9f18787*'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.6'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [78cc5f1a1db475e43cbf047e506025f0, clickElement {id=f.23F93CE1BF93211E4D645FB6F692C8E1.d.30306C07CA3B3E518F381EF26A5EAFEF.e.91}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 136.0.7103.114, chrome: {chromedriverVersion: 136.0.7103.113 (76fa3c17824..., userDataDir: C:\Users\ssmit\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:49721}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: Windows 10, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://192.168.1.191:4444/ses..., se:cdpVersion: 136.0.7103.114, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[RemoteWebDriver: chrome on Windows 10 (78cc5f1a1db475e43cbf047e506025f0)] -> xpath: //button[normalize-space()='Login']]
Session ID: 78cc5f1a1db475e43cbf047e506025f0. Screenshot: C:\Users\ssmit\eclipse-workspace\NinjaV5\screenshots\exception_smitasharma_qa_gmail_com_20250526074854.png]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unexpected exception during login for email: smitasharma.qa@gmail.com. Exception: element click intercepted: Element is not clickable at point (860, 571)
  (Session info: chrome=136.0.7103.114)
Build info: version: '4.31.0', revision: '1ef9f18787*'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.6'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [78cc5f1a1db475e43cbf047e506025f0, clickElement {id=f.23F93CE1BF93211E4D645FB6F692C8E1.d.30306C07CA3B3E518F381EF26A5EAFEF.e.91}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 136.0.7103.114, chrome: {chromedriverVersion: 136.0.7103.113 (76fa3c17824..., userDataDir: C:\Users\ssmit\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:49721}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: Windows 10, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://192.168.1.191:4444/ses..., se:cdpVersion: 136.0.7103.114, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[RemoteWebDriver: chrome on Windows 10 (78cc5f1a1db475e43cbf047e506025f0)] -> xpath: //button[normalize-space()='Login']]
Session ID: 78cc5f1a1db475e43cbf047e506025f0. Screenshot: C:\Users\ssmit\eclipse-workspace\NinjaV5\screenshots\exception_smitasharma_qa_gmail_com_20250526074854.png
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC02_Login.testLogin(TC02_Login.java:70)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method retried="true" signature="testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@561868a0]" started-at="2025-05-26T19:48:55 CDT" name="testLogin" data-provider="LoginData" finished-at="2025-05-26T19:48:56 CDT" duration-ms="1349" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[nona@yahoo.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[QWER!@#$]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unexpected exception during login for email: nona@yahoo.com. Exception: element click intercepted: Element is not clickable at point (774, -26)
  (Session info: chrome=136.0.7103.114)
Build info: version: '4.31.0', revision: '1ef9f18787*'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.6'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [78cc5f1a1db475e43cbf047e506025f0, clickElement {id=f.23F93CE1BF93211E4D645FB6F692C8E1.d.30306C07CA3B3E518F381EF26A5EAFEF.e.102}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 136.0.7103.114, chrome: {chromedriverVersion: 136.0.7103.113 (76fa3c17824..., userDataDir: C:\Users\ssmit\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:49721}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: Windows 10, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://192.168.1.191:4444/ses..., se:cdpVersion: 136.0.7103.114, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[RemoteWebDriver: chrome on Windows 10 (78cc5f1a1db475e43cbf047e506025f0)] -> xpath: //i[@class='fa-solid fa-user']]
Session ID: 78cc5f1a1db475e43cbf047e506025f0. Screenshot: C:\Users\ssmit\eclipse-workspace\NinjaV5\screenshots\exception_nona_yahoo_com_20250526074856.png]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unexpected exception during login for email: nona@yahoo.com. Exception: element click intercepted: Element is not clickable at point (774, -26)
  (Session info: chrome=136.0.7103.114)
Build info: version: '4.31.0', revision: '1ef9f18787*'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.6'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [78cc5f1a1db475e43cbf047e506025f0, clickElement {id=f.23F93CE1BF93211E4D645FB6F692C8E1.d.30306C07CA3B3E518F381EF26A5EAFEF.e.102}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 136.0.7103.114, chrome: {chromedriverVersion: 136.0.7103.113 (76fa3c17824..., userDataDir: C:\Users\ssmit\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:49721}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: Windows 10, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://192.168.1.191:4444/ses..., se:cdpVersion: 136.0.7103.114, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[RemoteWebDriver: chrome on Windows 10 (78cc5f1a1db475e43cbf047e506025f0)] -> xpath: //i[@class='fa-solid fa-user']]
Session ID: 78cc5f1a1db475e43cbf047e506025f0. Screenshot: C:\Users\ssmit\eclipse-workspace\NinjaV5\screenshots\exception_nona_yahoo_com_20250526074856.png
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC02_Login.testLogin(TC02_Login.java:70)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method retried="true" signature="testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@561868a0]" started-at="2025-05-26T19:48:56 CDT" name="testLogin" data-provider="LoginData" finished-at="2025-05-26T19:48:57 CDT" duration-ms="1285" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[nona@yahoo.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[QWER!@#$]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unexpected exception during login for email: nona@yahoo.com. Exception: element click intercepted: Element is not clickable at point (774, -24)
  (Session info: chrome=136.0.7103.114)
Build info: version: '4.31.0', revision: '1ef9f18787*'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.6'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [78cc5f1a1db475e43cbf047e506025f0, clickElement {id=f.23F93CE1BF93211E4D645FB6F692C8E1.d.30306C07CA3B3E518F381EF26A5EAFEF.e.102}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 136.0.7103.114, chrome: {chromedriverVersion: 136.0.7103.113 (76fa3c17824..., userDataDir: C:\Users\ssmit\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:49721}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: Windows 10, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://192.168.1.191:4444/ses..., se:cdpVersion: 136.0.7103.114, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[RemoteWebDriver: chrome on Windows 10 (78cc5f1a1db475e43cbf047e506025f0)] -> xpath: //i[@class='fa-solid fa-user']]
Session ID: 78cc5f1a1db475e43cbf047e506025f0. Screenshot: C:\Users\ssmit\eclipse-workspace\NinjaV5\screenshots\exception_nona_yahoo_com_20250526074857.png]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unexpected exception during login for email: nona@yahoo.com. Exception: element click intercepted: Element is not clickable at point (774, -24)
  (Session info: chrome=136.0.7103.114)
Build info: version: '4.31.0', revision: '1ef9f18787*'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.6'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [78cc5f1a1db475e43cbf047e506025f0, clickElement {id=f.23F93CE1BF93211E4D645FB6F692C8E1.d.30306C07CA3B3E518F381EF26A5EAFEF.e.102}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 136.0.7103.114, chrome: {chromedriverVersion: 136.0.7103.113 (76fa3c17824..., userDataDir: C:\Users\ssmit\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:49721}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: Windows 10, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://192.168.1.191:4444/ses..., se:cdpVersion: 136.0.7103.114, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[RemoteWebDriver: chrome on Windows 10 (78cc5f1a1db475e43cbf047e506025f0)] -> xpath: //i[@class='fa-solid fa-user']]
Session ID: 78cc5f1a1db475e43cbf047e506025f0. Screenshot: C:\Users\ssmit\eclipse-workspace\NinjaV5\screenshots\exception_nona_yahoo_com_20250526074857.png
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC02_Login.testLogin(TC02_Login.java:70)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method signature="testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@561868a0]" started-at="2025-05-26T19:48:57 CDT" name="testLogin" data-provider="LoginData" finished-at="2025-05-26T19:48:58 CDT" duration-ms="1201" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[nona@yahoo.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[QWER!@#$]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unexpected exception during login for email: nona@yahoo.com. Exception: element click intercepted: Element is not clickable at point (774, -18)
  (Session info: chrome=136.0.7103.114)
Build info: version: '4.31.0', revision: '1ef9f18787*'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.6'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [78cc5f1a1db475e43cbf047e506025f0, clickElement {id=f.23F93CE1BF93211E4D645FB6F692C8E1.d.30306C07CA3B3E518F381EF26A5EAFEF.e.102}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 136.0.7103.114, chrome: {chromedriverVersion: 136.0.7103.113 (76fa3c17824..., userDataDir: C:\Users\ssmit\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:49721}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: Windows 10, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://192.168.1.191:4444/ses..., se:cdpVersion: 136.0.7103.114, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[RemoteWebDriver: chrome on Windows 10 (78cc5f1a1db475e43cbf047e506025f0)] -> xpath: //i[@class='fa-solid fa-user']]
Session ID: 78cc5f1a1db475e43cbf047e506025f0. Screenshot: C:\Users\ssmit\eclipse-workspace\NinjaV5\screenshots\exception_nona_yahoo_com_20250526074858.png]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unexpected exception during login for email: nona@yahoo.com. Exception: element click intercepted: Element is not clickable at point (774, -18)
  (Session info: chrome=136.0.7103.114)
Build info: version: '4.31.0', revision: '1ef9f18787*'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.6'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [78cc5f1a1db475e43cbf047e506025f0, clickElement {id=f.23F93CE1BF93211E4D645FB6F692C8E1.d.30306C07CA3B3E518F381EF26A5EAFEF.e.102}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 136.0.7103.114, chrome: {chromedriverVersion: 136.0.7103.113 (76fa3c17824..., userDataDir: C:\Users\ssmit\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:49721}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: Windows 10, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://192.168.1.191:4444/ses..., se:cdpVersion: 136.0.7103.114, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[RemoteWebDriver: chrome on Windows 10 (78cc5f1a1db475e43cbf047e506025f0)] -> xpath: //i[@class='fa-solid fa-user']]
Session ID: 78cc5f1a1db475e43cbf047e506025f0. Screenshot: C:\Users\ssmit\eclipse-workspace\NinjaV5\screenshots\exception_nona_yahoo_com_20250526074858.png
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC02_Login.testLogin(TC02_Login.java:70)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method retried="true" signature="testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@561868a0]" started-at="2025-05-26T19:48:59 CDT" name="testLogin" data-provider="LoginData" finished-at="2025-05-26T19:49:00 CDT" duration-ms="1241" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[sid@cloudberry.services]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Test123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unexpected exception during login for email: sid@cloudberry.services. Exception: element click intercepted: Element is not clickable at point (774, -13)
  (Session info: chrome=136.0.7103.114)
Build info: version: '4.31.0', revision: '1ef9f18787*'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.6'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [78cc5f1a1db475e43cbf047e506025f0, clickElement {id=f.23F93CE1BF93211E4D645FB6F692C8E1.d.30306C07CA3B3E518F381EF26A5EAFEF.e.102}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 136.0.7103.114, chrome: {chromedriverVersion: 136.0.7103.113 (76fa3c17824..., userDataDir: C:\Users\ssmit\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:49721}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: Windows 10, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://192.168.1.191:4444/ses..., se:cdpVersion: 136.0.7103.114, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[RemoteWebDriver: chrome on Windows 10 (78cc5f1a1db475e43cbf047e506025f0)] -> xpath: //i[@class='fa-solid fa-user']]
Session ID: 78cc5f1a1db475e43cbf047e506025f0. Screenshot: C:\Users\ssmit\eclipse-workspace\NinjaV5\screenshots\exception_sid_cloudberry_services_20250526074900.png]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unexpected exception during login for email: sid@cloudberry.services. Exception: element click intercepted: Element is not clickable at point (774, -13)
  (Session info: chrome=136.0.7103.114)
Build info: version: '4.31.0', revision: '1ef9f18787*'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.6'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [78cc5f1a1db475e43cbf047e506025f0, clickElement {id=f.23F93CE1BF93211E4D645FB6F692C8E1.d.30306C07CA3B3E518F381EF26A5EAFEF.e.102}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 136.0.7103.114, chrome: {chromedriverVersion: 136.0.7103.113 (76fa3c17824..., userDataDir: C:\Users\ssmit\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:49721}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: Windows 10, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://192.168.1.191:4444/ses..., se:cdpVersion: 136.0.7103.114, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[RemoteWebDriver: chrome on Windows 10 (78cc5f1a1db475e43cbf047e506025f0)] -> xpath: //i[@class='fa-solid fa-user']]
Session ID: 78cc5f1a1db475e43cbf047e506025f0. Screenshot: C:\Users\ssmit\eclipse-workspace\NinjaV5\screenshots\exception_sid_cloudberry_services_20250526074900.png
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC02_Login.testLogin(TC02_Login.java:70)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method retried="true" signature="testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@561868a0]" started-at="2025-05-26T19:49:00 CDT" name="testLogin" data-provider="LoginData" finished-at="2025-05-26T19:49:01 CDT" duration-ms="1258" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[sid@cloudberry.services]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Test123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unexpected exception during login for email: sid@cloudberry.services. Exception: element click intercepted: Element is not clickable at point (774, -8)
  (Session info: chrome=136.0.7103.114)
Build info: version: '4.31.0', revision: '1ef9f18787*'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.6'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [78cc5f1a1db475e43cbf047e506025f0, clickElement {id=f.23F93CE1BF93211E4D645FB6F692C8E1.d.30306C07CA3B3E518F381EF26A5EAFEF.e.102}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 136.0.7103.114, chrome: {chromedriverVersion: 136.0.7103.113 (76fa3c17824..., userDataDir: C:\Users\ssmit\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:49721}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: Windows 10, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://192.168.1.191:4444/ses..., se:cdpVersion: 136.0.7103.114, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[RemoteWebDriver: chrome on Windows 10 (78cc5f1a1db475e43cbf047e506025f0)] -> xpath: //i[@class='fa-solid fa-user']]
Session ID: 78cc5f1a1db475e43cbf047e506025f0. Screenshot: C:\Users\ssmit\eclipse-workspace\NinjaV5\screenshots\exception_sid_cloudberry_services_20250526074901.png]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unexpected exception during login for email: sid@cloudberry.services. Exception: element click intercepted: Element is not clickable at point (774, -8)
  (Session info: chrome=136.0.7103.114)
Build info: version: '4.31.0', revision: '1ef9f18787*'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.6'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [78cc5f1a1db475e43cbf047e506025f0, clickElement {id=f.23F93CE1BF93211E4D645FB6F692C8E1.d.30306C07CA3B3E518F381EF26A5EAFEF.e.102}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 136.0.7103.114, chrome: {chromedriverVersion: 136.0.7103.113 (76fa3c17824..., userDataDir: C:\Users\ssmit\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:49721}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: Windows 10, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://192.168.1.191:4444/ses..., se:cdpVersion: 136.0.7103.114, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[RemoteWebDriver: chrome on Windows 10 (78cc5f1a1db475e43cbf047e506025f0)] -> xpath: //i[@class='fa-solid fa-user']]
Session ID: 78cc5f1a1db475e43cbf047e506025f0. Screenshot: C:\Users\ssmit\eclipse-workspace\NinjaV5\screenshots\exception_sid_cloudberry_services_20250526074901.png
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC02_Login.testLogin(TC02_Login.java:70)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method signature="testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@561868a0]" started-at="2025-05-26T19:49:01 CDT" name="testLogin" data-provider="LoginData" finished-at="2025-05-26T19:49:03 CDT" duration-ms="1825" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[sid@cloudberry.services]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Test123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unexpected exception during login for email: sid@cloudberry.services. Exception: element click intercepted: Element is not clickable at point (860, 571)
  (Session info: chrome=136.0.7103.114)
Build info: version: '4.31.0', revision: '1ef9f18787*'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.6'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [78cc5f1a1db475e43cbf047e506025f0, clickElement {id=f.23F93CE1BF93211E4D645FB6F692C8E1.d.82C3E9D4F6B455ED567F6684681D66CD.e.115}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 136.0.7103.114, chrome: {chromedriverVersion: 136.0.7103.113 (76fa3c17824..., userDataDir: C:\Users\ssmit\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:49721}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: Windows 10, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://192.168.1.191:4444/ses..., se:cdpVersion: 136.0.7103.114, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[RemoteWebDriver: chrome on Windows 10 (78cc5f1a1db475e43cbf047e506025f0)] -> xpath: //button[normalize-space()='Login']]
Session ID: 78cc5f1a1db475e43cbf047e506025f0. Screenshot: C:\Users\ssmit\eclipse-workspace\NinjaV5\screenshots\exception_sid_cloudberry_services_20250526074903.png]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unexpected exception during login for email: sid@cloudberry.services. Exception: element click intercepted: Element is not clickable at point (860, 571)
  (Session info: chrome=136.0.7103.114)
Build info: version: '4.31.0', revision: '1ef9f18787*'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.6'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [78cc5f1a1db475e43cbf047e506025f0, clickElement {id=f.23F93CE1BF93211E4D645FB6F692C8E1.d.82C3E9D4F6B455ED567F6684681D66CD.e.115}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 136.0.7103.114, chrome: {chromedriverVersion: 136.0.7103.113 (76fa3c17824..., userDataDir: C:\Users\ssmit\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:49721}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: Windows 10, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://192.168.1.191:4444/ses..., se:cdpVersion: 136.0.7103.114, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[RemoteWebDriver: chrome on Windows 10 (78cc5f1a1db475e43cbf047e506025f0)] -> xpath: //button[normalize-space()='Login']]
Session ID: 78cc5f1a1db475e43cbf047e506025f0. Screenshot: C:\Users\ssmit\eclipse-workspace\NinjaV5\screenshots\exception_sid_cloudberry_services_20250526074903.png
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC02_Login.testLogin(TC02_Login.java:70)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method retried="true" signature="testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@561868a0]" started-at="2025-05-26T19:49:03 CDT" name="testLogin" data-provider="LoginData" finished-at="2025-05-26T19:49:05 CDT" duration-ms="1862" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[apushedwoman@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[password123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unexpected exception during login for email: apushedwoman@gmail.com. Exception: element click intercepted: Element is not clickable at point (860, 571)
  (Session info: chrome=136.0.7103.114)
Build info: version: '4.31.0', revision: '1ef9f18787*'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.6'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [78cc5f1a1db475e43cbf047e506025f0, clickElement {id=f.23F93CE1BF93211E4D645FB6F692C8E1.d.7D7000B63326FE56EF825798E4A2D02D.e.136}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 136.0.7103.114, chrome: {chromedriverVersion: 136.0.7103.113 (76fa3c17824..., userDataDir: C:\Users\ssmit\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:49721}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: Windows 10, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://192.168.1.191:4444/ses..., se:cdpVersion: 136.0.7103.114, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[RemoteWebDriver: chrome on Windows 10 (78cc5f1a1db475e43cbf047e506025f0)] -> xpath: //button[normalize-space()='Login']]
Session ID: 78cc5f1a1db475e43cbf047e506025f0. Screenshot: C:\Users\ssmit\eclipse-workspace\NinjaV5\screenshots\exception_apushedwoman_gmail_com_20250526074905.png]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unexpected exception during login for email: apushedwoman@gmail.com. Exception: element click intercepted: Element is not clickable at point (860, 571)
  (Session info: chrome=136.0.7103.114)
Build info: version: '4.31.0', revision: '1ef9f18787*'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.6'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [78cc5f1a1db475e43cbf047e506025f0, clickElement {id=f.23F93CE1BF93211E4D645FB6F692C8E1.d.7D7000B63326FE56EF825798E4A2D02D.e.136}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 136.0.7103.114, chrome: {chromedriverVersion: 136.0.7103.113 (76fa3c17824..., userDataDir: C:\Users\ssmit\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:49721}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: Windows 10, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://192.168.1.191:4444/ses..., se:cdpVersion: 136.0.7103.114, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[RemoteWebDriver: chrome on Windows 10 (78cc5f1a1db475e43cbf047e506025f0)] -> xpath: //button[normalize-space()='Login']]
Session ID: 78cc5f1a1db475e43cbf047e506025f0. Screenshot: C:\Users\ssmit\eclipse-workspace\NinjaV5\screenshots\exception_apushedwoman_gmail_com_20250526074905.png
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC02_Login.testLogin(TC02_Login.java:70)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method retried="true" signature="testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@561868a0]" started-at="2025-05-26T19:49:05 CDT" name="testLogin" data-provider="LoginData" finished-at="2025-05-26T19:49:07 CDT" duration-ms="1755" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[apushedwoman@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[password123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unexpected exception during login for email: apushedwoman@gmail.com. Exception: element click intercepted: Element is not clickable at point (860, 571)
  (Session info: chrome=136.0.7103.114)
Build info: version: '4.31.0', revision: '1ef9f18787*'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.6'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [78cc5f1a1db475e43cbf047e506025f0, clickElement {id=f.23F93CE1BF93211E4D645FB6F692C8E1.d.D78B62F37FDE78B7D022872F8375BC37.e.156}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 136.0.7103.114, chrome: {chromedriverVersion: 136.0.7103.113 (76fa3c17824..., userDataDir: C:\Users\ssmit\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:49721}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: Windows 10, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://192.168.1.191:4444/ses..., se:cdpVersion: 136.0.7103.114, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[RemoteWebDriver: chrome on Windows 10 (78cc5f1a1db475e43cbf047e506025f0)] -> xpath: //button[normalize-space()='Login']]
Session ID: 78cc5f1a1db475e43cbf047e506025f0. Screenshot: C:\Users\ssmit\eclipse-workspace\NinjaV5\screenshots\exception_apushedwoman_gmail_com_20250526074906.png]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unexpected exception during login for email: apushedwoman@gmail.com. Exception: element click intercepted: Element is not clickable at point (860, 571)
  (Session info: chrome=136.0.7103.114)
Build info: version: '4.31.0', revision: '1ef9f18787*'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.6'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [78cc5f1a1db475e43cbf047e506025f0, clickElement {id=f.23F93CE1BF93211E4D645FB6F692C8E1.d.D78B62F37FDE78B7D022872F8375BC37.e.156}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 136.0.7103.114, chrome: {chromedriverVersion: 136.0.7103.113 (76fa3c17824..., userDataDir: C:\Users\ssmit\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:49721}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: Windows 10, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://192.168.1.191:4444/ses..., se:cdpVersion: 136.0.7103.114, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[RemoteWebDriver: chrome on Windows 10 (78cc5f1a1db475e43cbf047e506025f0)] -> xpath: //button[normalize-space()='Login']]
Session ID: 78cc5f1a1db475e43cbf047e506025f0. Screenshot: C:\Users\ssmit\eclipse-workspace\NinjaV5\screenshots\exception_apushedwoman_gmail_com_20250526074906.png
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC02_Login.testLogin(TC02_Login.java:70)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method signature="testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@561868a0]" started-at="2025-05-26T19:49:07 CDT" name="testLogin" data-provider="LoginData" finished-at="2025-05-26T19:49:09 CDT" duration-ms="2027" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[apushedwoman@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[password123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unexpected exception during login for email: apushedwoman@gmail.com. Exception: element click intercepted: Element is not clickable at point (860, 571)
  (Session info: chrome=136.0.7103.114)
Build info: version: '4.31.0', revision: '1ef9f18787*'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.6'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [78cc5f1a1db475e43cbf047e506025f0, clickElement {id=f.23F93CE1BF93211E4D645FB6F692C8E1.d.2D8A684E14F78555CD0F8D7D2EE5E6BE.e.177}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 136.0.7103.114, chrome: {chromedriverVersion: 136.0.7103.113 (76fa3c17824..., userDataDir: C:\Users\ssmit\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:49721}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: Windows 10, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://192.168.1.191:4444/ses..., se:cdpVersion: 136.0.7103.114, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[RemoteWebDriver: chrome on Windows 10 (78cc5f1a1db475e43cbf047e506025f0)] -> xpath: //button[normalize-space()='Login']]
Session ID: 78cc5f1a1db475e43cbf047e506025f0. Screenshot: C:\Users\ssmit\eclipse-workspace\NinjaV5\screenshots\exception_apushedwoman_gmail_com_20250526074908.png]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unexpected exception during login for email: apushedwoman@gmail.com. Exception: element click intercepted: Element is not clickable at point (860, 571)
  (Session info: chrome=136.0.7103.114)
Build info: version: '4.31.0', revision: '1ef9f18787*'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.6'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [78cc5f1a1db475e43cbf047e506025f0, clickElement {id=f.23F93CE1BF93211E4D645FB6F692C8E1.d.2D8A684E14F78555CD0F8D7D2EE5E6BE.e.177}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 136.0.7103.114, chrome: {chromedriverVersion: 136.0.7103.113 (76fa3c17824..., userDataDir: C:\Users\ssmit\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:49721}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: Windows 10, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://192.168.1.191:4444/ses..., se:cdpVersion: 136.0.7103.114, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[RemoteWebDriver: chrome on Windows 10 (78cc5f1a1db475e43cbf047e506025f0)] -> xpath: //button[normalize-space()='Login']]
Session ID: 78cc5f1a1db475e43cbf047e506025f0. Screenshot: C:\Users\ssmit\eclipse-workspace\NinjaV5\screenshots\exception_apushedwoman_gmail_com_20250526074908.png
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC02_Login.testLogin(TC02_Login.java:70)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method retried="true" signature="testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@561868a0]" started-at="2025-05-26T19:49:09 CDT" name="testLogin" data-provider="LoginData" finished-at="2025-05-26T19:49:10 CDT" duration-ms="1308" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[hichamkhachiai@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[hicham123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unexpected exception during login for email: hichamkhachiai@gmail.com. Exception: element click intercepted: Element is not clickable at point (774, -26)
  (Session info: chrome=136.0.7103.114)
Build info: version: '4.31.0', revision: '1ef9f18787*'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.6'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [78cc5f1a1db475e43cbf047e506025f0, clickElement {id=f.23F93CE1BF93211E4D645FB6F692C8E1.d.2D8A684E14F78555CD0F8D7D2EE5E6BE.e.187}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 136.0.7103.114, chrome: {chromedriverVersion: 136.0.7103.113 (76fa3c17824..., userDataDir: C:\Users\ssmit\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:49721}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: Windows 10, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://192.168.1.191:4444/ses..., se:cdpVersion: 136.0.7103.114, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[RemoteWebDriver: chrome on Windows 10 (78cc5f1a1db475e43cbf047e506025f0)] -> xpath: //i[@class='fa-solid fa-user']]
Session ID: 78cc5f1a1db475e43cbf047e506025f0. Screenshot: C:\Users\ssmit\eclipse-workspace\NinjaV5\screenshots\exception_hichamkhachiai_gmail_com_20250526074910.png]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unexpected exception during login for email: hichamkhachiai@gmail.com. Exception: element click intercepted: Element is not clickable at point (774, -26)
  (Session info: chrome=136.0.7103.114)
Build info: version: '4.31.0', revision: '1ef9f18787*'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.6'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [78cc5f1a1db475e43cbf047e506025f0, clickElement {id=f.23F93CE1BF93211E4D645FB6F692C8E1.d.2D8A684E14F78555CD0F8D7D2EE5E6BE.e.187}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 136.0.7103.114, chrome: {chromedriverVersion: 136.0.7103.113 (76fa3c17824..., userDataDir: C:\Users\ssmit\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:49721}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: Windows 10, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://192.168.1.191:4444/ses..., se:cdpVersion: 136.0.7103.114, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[RemoteWebDriver: chrome on Windows 10 (78cc5f1a1db475e43cbf047e506025f0)] -> xpath: //i[@class='fa-solid fa-user']]
Session ID: 78cc5f1a1db475e43cbf047e506025f0. Screenshot: C:\Users\ssmit\eclipse-workspace\NinjaV5\screenshots\exception_hichamkhachiai_gmail_com_20250526074910.png
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC02_Login.testLogin(TC02_Login.java:70)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method retried="true" signature="testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@561868a0]" started-at="2025-05-26T19:49:10 CDT" name="testLogin" data-provider="LoginData" finished-at="2025-05-26T19:49:11 CDT" duration-ms="1303" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[hichamkhachiai@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[hicham123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unexpected exception during login for email: hichamkhachiai@gmail.com. Exception: element click intercepted: Element is not clickable at point (774, -24)
  (Session info: chrome=136.0.7103.114)
Build info: version: '4.31.0', revision: '1ef9f18787*'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.6'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [78cc5f1a1db475e43cbf047e506025f0, clickElement {id=f.23F93CE1BF93211E4D645FB6F692C8E1.d.2D8A684E14F78555CD0F8D7D2EE5E6BE.e.187}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 136.0.7103.114, chrome: {chromedriverVersion: 136.0.7103.113 (76fa3c17824..., userDataDir: C:\Users\ssmit\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:49721}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: Windows 10, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://192.168.1.191:4444/ses..., se:cdpVersion: 136.0.7103.114, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[RemoteWebDriver: chrome on Windows 10 (78cc5f1a1db475e43cbf047e506025f0)] -> xpath: //i[@class='fa-solid fa-user']]
Session ID: 78cc5f1a1db475e43cbf047e506025f0. Screenshot: C:\Users\ssmit\eclipse-workspace\NinjaV5\screenshots\exception_hichamkhachiai_gmail_com_20250526074911.png]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unexpected exception during login for email: hichamkhachiai@gmail.com. Exception: element click intercepted: Element is not clickable at point (774, -24)
  (Session info: chrome=136.0.7103.114)
Build info: version: '4.31.0', revision: '1ef9f18787*'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.6'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [78cc5f1a1db475e43cbf047e506025f0, clickElement {id=f.23F93CE1BF93211E4D645FB6F692C8E1.d.2D8A684E14F78555CD0F8D7D2EE5E6BE.e.187}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 136.0.7103.114, chrome: {chromedriverVersion: 136.0.7103.113 (76fa3c17824..., userDataDir: C:\Users\ssmit\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:49721}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: Windows 10, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://192.168.1.191:4444/ses..., se:cdpVersion: 136.0.7103.114, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[RemoteWebDriver: chrome on Windows 10 (78cc5f1a1db475e43cbf047e506025f0)] -> xpath: //i[@class='fa-solid fa-user']]
Session ID: 78cc5f1a1db475e43cbf047e506025f0. Screenshot: C:\Users\ssmit\eclipse-workspace\NinjaV5\screenshots\exception_hichamkhachiai_gmail_com_20250526074911.png
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC02_Login.testLogin(TC02_Login.java:70)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method signature="testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@561868a0]" started-at="2025-05-26T19:49:11 CDT" name="testLogin" data-provider="LoginData" finished-at="2025-05-26T19:49:13 CDT" duration-ms="1341" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[hichamkhachiai@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[hicham123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unexpected exception during login for email: hichamkhachiai@gmail.com. Exception: element click intercepted: Element is not clickable at point (774, -18)
  (Session info: chrome=136.0.7103.114)
Build info: version: '4.31.0', revision: '1ef9f18787*'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.6'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [78cc5f1a1db475e43cbf047e506025f0, clickElement {id=f.23F93CE1BF93211E4D645FB6F692C8E1.d.2D8A684E14F78555CD0F8D7D2EE5E6BE.e.187}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 136.0.7103.114, chrome: {chromedriverVersion: 136.0.7103.113 (76fa3c17824..., userDataDir: C:\Users\ssmit\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:49721}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: Windows 10, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://192.168.1.191:4444/ses..., se:cdpVersion: 136.0.7103.114, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[RemoteWebDriver: chrome on Windows 10 (78cc5f1a1db475e43cbf047e506025f0)] -> xpath: //i[@class='fa-solid fa-user']]
Session ID: 78cc5f1a1db475e43cbf047e506025f0. Screenshot: C:\Users\ssmit\eclipse-workspace\NinjaV5\screenshots\exception_hichamkhachiai_gmail_com_20250526074913.png]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unexpected exception during login for email: hichamkhachiai@gmail.com. Exception: element click intercepted: Element is not clickable at point (774, -18)
  (Session info: chrome=136.0.7103.114)
Build info: version: '4.31.0', revision: '1ef9f18787*'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.6'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [78cc5f1a1db475e43cbf047e506025f0, clickElement {id=f.23F93CE1BF93211E4D645FB6F692C8E1.d.2D8A684E14F78555CD0F8D7D2EE5E6BE.e.187}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 136.0.7103.114, chrome: {chromedriverVersion: 136.0.7103.113 (76fa3c17824..., userDataDir: C:\Users\ssmit\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:49721}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: Windows 10, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://192.168.1.191:4444/ses..., se:cdpVersion: 136.0.7103.114, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[RemoteWebDriver: chrome on Windows 10 (78cc5f1a1db475e43cbf047e506025f0)] -> xpath: //i[@class='fa-solid fa-user']]
Session ID: 78cc5f1a1db475e43cbf047e506025f0. Screenshot: C:\Users\ssmit\eclipse-workspace\NinjaV5\screenshots\exception_hichamkhachiai_gmail_com_20250526074913.png
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC02_Login.testLogin(TC02_Login.java:70)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method is-config="true" signature="closeApp()[pri:0, instance:testCases.TC02_Login@561868a0]" started-at="2025-05-26T19:49:13 CDT" name="closeApp" finished-at="2025-05-26T19:49:16 CDT" duration-ms="3201" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- testCases.TC02_Login -->
      <class name="testCases.TC05_AddToWishList">
        <test-method is-config="true" signature="openApp(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC05_AddToWishList@6155d082]" started-at="2025-05-26T19:48:19 CDT" name="openApp" finished-at="2025-05-26T19:48:24 CDT" duration-ms="4249" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method retried="true" signature="testAddToWishList()[pri:0, instance:testCases.TC05_AddToWishList@6155d082]" started-at="2025-05-26T19:48:24 CDT" name="testAddToWishList" finished-at="2025-05-26T19:48:27 CDT" duration-ms="2836" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed due to unexpected exception.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed due to unexpected exception.
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC05_AddToWishList.testAddToWishList(TC05_AddToWishList.java:77)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddToWishList -->
        <test-method retried="true" signature="testAddToWishList()[pri:0, instance:testCases.TC05_AddToWishList@6155d082]" started-at="2025-05-26T19:48:27 CDT" name="testAddToWishList" finished-at="2025-05-26T19:48:29 CDT" duration-ms="2115" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed due to unexpected exception.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed due to unexpected exception.
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC05_AddToWishList.testAddToWishList(TC05_AddToWishList.java:77)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddToWishList -->
        <test-method signature="testAddToWishList()[pri:0, instance:testCases.TC05_AddToWishList@6155d082]" started-at="2025-05-26T19:48:29 CDT" name="testAddToWishList" finished-at="2025-05-26T19:48:31 CDT" duration-ms="1923" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed due to unexpected exception.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed due to unexpected exception.
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC05_AddToWishList.testAddToWishList(TC05_AddToWishList.java:77)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddToWishList -->
        <test-method is-config="true" signature="closeApp()[pri:0, instance:testCases.TC05_AddToWishList@6155d082]" started-at="2025-05-26T19:48:31 CDT" name="closeApp" finished-at="2025-05-26T19:48:34 CDT" duration-ms="3066" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- testCases.TC05_AddToWishList -->
      <class name="testCases.TC01_LaunchApplication">
        <test-method is-config="true" signature="openApp(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC01_LaunchApplication@1fde5d22]" started-at="2025-05-26T19:48:02 CDT" name="openApp" finished-at="2025-05-26T19:48:08 CDT" duration-ms="6217" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method signature="testLaunchApplication()[pri:0, instance:testCases.TC01_LaunchApplication@1fde5d22]" started-at="2025-05-26T19:48:08 CDT" name="testLaunchApplication" finished-at="2025-05-26T19:48:08 CDT" duration-ms="27" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLaunchApplication -->
        <test-method is-config="true" signature="closeApp()[pri:0, instance:testCases.TC01_LaunchApplication@1fde5d22]" started-at="2025-05-26T19:48:08 CDT" name="closeApp" finished-at="2025-05-26T19:48:09 CDT" duration-ms="1129" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- testCases.TC01_LaunchApplication -->
      <class name="testCases.TC03_AddToCart">
        <test-method is-config="true" signature="openApp(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC03_AddToCart@47f9738]" started-at="2025-05-26T19:48:09 CDT" name="openApp" finished-at="2025-05-26T19:48:11 CDT" duration-ms="2279" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method signature="testAddToCart()[pri:0, instance:testCases.TC03_AddToCart@47f9738]" started-at="2025-05-26T19:48:11 CDT" name="testAddToCart" finished-at="2025-05-26T19:48:17 CDT" duration-ms="5811" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddToCart -->
        <test-method is-config="true" signature="closeApp()[pri:0, instance:testCases.TC03_AddToCart@47f9738]" started-at="2025-05-26T19:48:17 CDT" name="closeApp" finished-at="2025-05-26T19:48:19 CDT" duration-ms="2199" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- testCases.TC03_AddToCart -->
      <class name="testCases.TC06_AddAffiliate">
        <test-method is-config="true" signature="openApp(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC06_AddAffiliate@3a5ecce3]" started-at="2025-05-26T19:48:34 CDT" name="openApp" finished-at="2025-05-26T19:48:37 CDT" duration-ms="2903" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method retried="true" signature="testAddAffiliate()[pri:0, instance:testCases.TC06_AddAffiliate@3a5ecce3]" started-at="2025-05-26T19:48:37 CDT" name="testAddAffiliate" finished-at="2025-05-26T19:48:40 CDT" duration-ms="3446" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed due to unexpected exception.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed due to unexpected exception.
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC06_AddAffiliate.testAddAffiliate(TC06_AddAffiliate.java:60)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddAffiliate -->
        <test-method retried="true" signature="testAddAffiliate()[pri:0, instance:testCases.TC06_AddAffiliate@3a5ecce3]" started-at="2025-05-26T19:48:40 CDT" name="testAddAffiliate" finished-at="2025-05-26T19:48:42 CDT" duration-ms="1788" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed due to unexpected exception.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed due to unexpected exception.
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC06_AddAffiliate.testAddAffiliate(TC06_AddAffiliate.java:60)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddAffiliate -->
        <test-method signature="testAddAffiliate()[pri:0, instance:testCases.TC06_AddAffiliate@3a5ecce3]" started-at="2025-05-26T19:48:42 CDT" name="testAddAffiliate" finished-at="2025-05-26T19:48:44 CDT" duration-ms="1619" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed due to unexpected exception.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed due to unexpected exception.
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC06_AddAffiliate.testAddAffiliate(TC06_AddAffiliate.java:60)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddAffiliate -->
        <test-method is-config="true" signature="closeApp()[pri:0, instance:testCases.TC06_AddAffiliate@3a5ecce3]" started-at="2025-05-26T19:48:44 CDT" name="closeApp" finished-at="2025-05-26T19:48:44 CDT" duration-ms="190" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- testCases.TC06_AddAffiliate -->
      <class name="testCases.TC04_CompletePurchase">
        <test-method is-config="true" signature="openApp(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC04_CompletePurchase@2ea6e30c]" started-at="2025-05-26T19:49:16 CDT" name="openApp" finished-at="2025-05-26T19:49:19 CDT" duration-ms="2968" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method retried="true" signature="testCompletePurchase()[pri:0, instance:testCases.TC04_CompletePurchase@2ea6e30c]" started-at="2025-05-26T19:49:19 CDT" name="testCompletePurchase" finished-at="2025-05-26T19:49:26 CDT" duration-ms="7099" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed due to unexpected exception.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed due to unexpected exception.
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC04_CompletePurchase.testCompletePurchase(TC04_CompletePurchase.java:81)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCompletePurchase -->
        <test-method retried="true" signature="testCompletePurchase()[pri:0, instance:testCases.TC04_CompletePurchase@2ea6e30c]" started-at="2025-05-26T19:49:26 CDT" name="testCompletePurchase" finished-at="2025-05-26T19:49:40 CDT" duration-ms="13199" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed due to unexpected exception.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed due to unexpected exception.
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC04_CompletePurchase.testCompletePurchase(TC04_CompletePurchase.java:81)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCompletePurchase -->
        <test-method signature="testCompletePurchase()[pri:0, instance:testCases.TC04_CompletePurchase@2ea6e30c]" started-at="2025-05-26T19:49:40 CDT" name="testCompletePurchase" finished-at="2025-05-26T19:49:51 CDT" duration-ms="11924" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed due to unexpected exception.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed due to unexpected exception.
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC04_CompletePurchase.testCompletePurchase(TC04_CompletePurchase.java:81)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCompletePurchase -->
        <test-method is-config="true" signature="closeApp()[pri:0, instance:testCases.TC04_CompletePurchase@2ea6e30c]" started-at="2025-05-26T19:49:52 CDT" name="closeApp" finished-at="2025-05-26T19:49:52 CDT" duration-ms="655" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- testCases.TC04_CompletePurchase -->
    </test> <!-- chromeTest -->
    <test started-at="2025-05-26T19:48:02 CDT" name="edgeTest" finished-at="2025-05-26T19:50:02 CDT" duration-ms="120731">
      <class name="testCases.TC02_Login">
        <test-method is-config="true" signature="openApp(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@61a88b8c]" started-at="2025-05-26T19:49:19 CDT" name="openApp" finished-at="2025-05-26T19:49:23 CDT" duration-ms="3860" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[edge]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method signature="testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@61a88b8c]" started-at="2025-05-26T19:49:24 CDT" name="testLogin" data-provider="LoginData" finished-at="2025-05-26T19:49:26 CDT" duration-ms="2273" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[smitasharma.qa@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[ss*QA123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method signature="testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@61a88b8c]" started-at="2025-05-26T19:49:26 CDT" name="testLogin" data-provider="LoginData" finished-at="2025-05-26T19:49:30 CDT" duration-ms="3121" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[nona@yahoo.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[QWER!@#$]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method signature="testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@61a88b8c]" started-at="2025-05-26T19:49:30 CDT" name="testLogin" data-provider="LoginData" finished-at="2025-05-26T19:49:33 CDT" duration-ms="3238" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[sid@cloudberry.services]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Test123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method signature="testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@61a88b8c]" started-at="2025-05-26T19:49:33 CDT" name="testLogin" data-provider="LoginData" finished-at="2025-05-26T19:49:35 CDT" duration-ms="2234" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[apushedwoman@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[password123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method signature="testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@61a88b8c]" started-at="2025-05-26T19:49:35 CDT" name="testLogin" data-provider="LoginData" finished-at="2025-05-26T19:49:37 CDT" duration-ms="1555" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[hichamkhachiai@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[hicham123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method is-config="true" signature="closeApp()[pri:0, instance:testCases.TC02_Login@61a88b8c]" started-at="2025-05-26T19:49:37 CDT" name="closeApp" finished-at="2025-05-26T19:49:38 CDT" duration-ms="1386" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- testCases.TC02_Login -->
      <class name="testCases.TC05_AddToWishList">
        <test-method is-config="true" signature="openApp(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC05_AddToWishList@512535ff]" started-at="2025-05-26T19:48:27 CDT" name="openApp" finished-at="2025-05-26T19:48:31 CDT" duration-ms="4598" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[edge]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method retried="true" signature="testAddToWishList()[pri:0, instance:testCases.TC05_AddToWishList@512535ff]" started-at="2025-05-26T19:48:31 CDT" name="testAddToWishList" finished-at="2025-05-26T19:48:45 CDT" duration-ms="13629" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed due to unexpected exception.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed due to unexpected exception.
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC05_AddToWishList.testAddToWishList(TC05_AddToWishList.java:77)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddToWishList -->
        <test-method retried="true" signature="testAddToWishList()[pri:0, instance:testCases.TC05_AddToWishList@512535ff]" started-at="2025-05-26T19:48:45 CDT" name="testAddToWishList" finished-at="2025-05-26T19:48:55 CDT" duration-ms="10348" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed due to unexpected exception.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed due to unexpected exception.
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC05_AddToWishList.testAddToWishList(TC05_AddToWishList.java:77)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddToWishList -->
        <test-method signature="testAddToWishList()[pri:0, instance:testCases.TC05_AddToWishList@512535ff]" started-at="2025-05-26T19:48:55 CDT" name="testAddToWishList" finished-at="2025-05-26T19:49:06 CDT" duration-ms="10282" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed due to unexpected exception.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed due to unexpected exception.
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC05_AddToWishList.testAddToWishList(TC05_AddToWishList.java:77)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddToWishList -->
        <test-method is-config="true" signature="closeApp()[pri:0, instance:testCases.TC05_AddToWishList@512535ff]" started-at="2025-05-26T19:49:06 CDT" name="closeApp" finished-at="2025-05-26T19:49:07 CDT" duration-ms="1428" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- testCases.TC05_AddToWishList -->
      <class name="testCases.TC01_LaunchApplication">
        <test-method is-config="true" signature="openApp(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC01_LaunchApplication@4f1bfe23]" started-at="2025-05-26T19:48:02 CDT" name="openApp" finished-at="2025-05-26T19:48:07 CDT" duration-ms="4716" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[edge]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method signature="testLaunchApplication()[pri:0, instance:testCases.TC01_LaunchApplication@4f1bfe23]" started-at="2025-05-26T19:48:07 CDT" name="testLaunchApplication" finished-at="2025-05-26T19:48:07 CDT" duration-ms="288" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLaunchApplication -->
        <test-method is-config="true" signature="closeApp()[pri:0, instance:testCases.TC01_LaunchApplication@4f1bfe23]" started-at="2025-05-26T19:48:07 CDT" name="closeApp" finished-at="2025-05-26T19:48:11 CDT" duration-ms="4510" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- testCases.TC01_LaunchApplication -->
      <class name="testCases.TC03_AddToCart">
        <test-method is-config="true" signature="openApp(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC03_AddToCart@e19bb76]" started-at="2025-05-26T19:48:11 CDT" name="openApp" finished-at="2025-05-26T19:48:15 CDT" duration-ms="3281" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[edge]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method retried="true" signature="testAddToCart()[pri:0, instance:testCases.TC03_AddToCart@e19bb76]" started-at="2025-05-26T19:48:15 CDT" name="testAddToCart" finished-at="2025-05-26T19:48:18 CDT" duration-ms="3092" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed due to unexpected exception.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed due to unexpected exception.
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC03_AddToCart.testAddToCart(TC03_AddToCart.java:55)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddToCart -->
        <test-method signature="testAddToCart()[pri:0, instance:testCases.TC03_AddToCart@e19bb76]" started-at="2025-05-26T19:48:18 CDT" name="testAddToCart" finished-at="2025-05-26T19:48:24 CDT" duration-ms="6325" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddToCart -->
        <test-method is-config="true" signature="closeApp()[pri:0, instance:testCases.TC03_AddToCart@e19bb76]" started-at="2025-05-26T19:48:24 CDT" name="closeApp" finished-at="2025-05-26T19:48:27 CDT" duration-ms="2549" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- testCases.TC03_AddToCart -->
      <class name="testCases.TC06_AddAffiliate">
        <test-method is-config="true" signature="openApp(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC06_AddAffiliate@71529963]" started-at="2025-05-26T19:49:07 CDT" name="openApp" finished-at="2025-05-26T19:49:10 CDT" duration-ms="2897" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[edge]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method signature="testAddAffiliate()[pri:0, instance:testCases.TC06_AddAffiliate@71529963]" started-at="2025-05-26T19:49:10 CDT" name="testAddAffiliate" finished-at="2025-05-26T19:49:16 CDT" duration-ms="5647" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddAffiliate -->
        <test-method is-config="true" signature="closeApp()[pri:0, instance:testCases.TC06_AddAffiliate@71529963]" started-at="2025-05-26T19:49:16 CDT" name="closeApp" finished-at="2025-05-26T19:49:19 CDT" duration-ms="3686" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- testCases.TC06_AddAffiliate -->
      <class name="testCases.TC04_CompletePurchase">
        <test-method is-config="true" signature="openApp(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC04_CompletePurchase@22295ec4]" started-at="2025-05-26T19:49:38 CDT" name="openApp" finished-at="2025-05-26T19:49:40 CDT" duration-ms="2082" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[edge]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method retried="true" signature="testCompletePurchase()[pri:0, instance:testCases.TC04_CompletePurchase@22295ec4]" started-at="2025-05-26T19:49:40 CDT" name="testCompletePurchase" finished-at="2025-05-26T19:49:44 CDT" duration-ms="3607" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed due to unexpected exception.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed due to unexpected exception.
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC04_CompletePurchase.testCompletePurchase(TC04_CompletePurchase.java:81)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCompletePurchase -->
        <test-method retried="true" signature="testCompletePurchase()[pri:0, instance:testCases.TC04_CompletePurchase@22295ec4]" started-at="2025-05-26T19:49:44 CDT" name="testCompletePurchase" finished-at="2025-05-26T19:49:49 CDT" duration-ms="5558" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed due to unexpected exception.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed due to unexpected exception.
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC04_CompletePurchase.testCompletePurchase(TC04_CompletePurchase.java:81)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCompletePurchase -->
        <test-method signature="testCompletePurchase()[pri:0, instance:testCases.TC04_CompletePurchase@22295ec4]" started-at="2025-05-26T19:49:49 CDT" name="testCompletePurchase" finished-at="2025-05-26T19:50:01 CDT" duration-ms="11683" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed due to unexpected exception.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed due to unexpected exception.
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC04_CompletePurchase.testCompletePurchase(TC04_CompletePurchase.java:81)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCompletePurchase -->
        <test-method is-config="true" signature="closeApp()[pri:0, instance:testCases.TC04_CompletePurchase@22295ec4]" started-at="2025-05-26T19:50:01 CDT" name="closeApp" finished-at="2025-05-26T19:50:02 CDT" duration-ms="1288" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- testCases.TC04_CompletePurchase -->
    </test> <!-- edgeTest -->
  </suite> <!-- Suite -->
</testng-results>
